apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webhooks.jannemattila.com
spec:
  group: jannemattila.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              uri:
                type: string
  scope: Namespaced
  names:
    plural: webhooks
    singular: webhook
    kind: Webhook
    shortNames:
     - wh
